---
Name: anyfield
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\AnyField\Extensions\LeftAndMain

SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\AnyField\Extensions\ModalController

SilverStripe\Forms\TreeDropdownField:
  extensions:
    - SilverStripe\AnyField\Extensions\AjaxField

SilverStripe\CMS\Forms\AnchorSelectorField:
  extensions:
    - SilverStripe\AnyField\Extensions\AjaxField
