---
Name: anyfield
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\AnyField\Extensions\SchemaControllerExtension

SilverStripe\Admin\ModalController:
  extensions:
    - SilverStripe\AnyField\Extensions\ModalControllerFormExtension

SilverStripe\Forms\TreeDropdownField:
  extensions:
    - SilverStripe\AnyField\Extensions\AjaxFieldLinkExtension

SilverStripe\CMS\Forms\AnchorSelectorField:
  extensions:
    - SilverStripe\AnyField\Extensions\AjaxFieldLinkExtension


SilverStripe\Core\Injector\Injector:
  SilverStripe\AnyField\Services\AnyService:
    class: SilverStripe\AnyField\Services\AnyService
